# Generated by Django 2.1.3 on 2018-11-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='query',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('repo', models.CharField(max_length=150)),
            ],
        ),
    ]
