# Generated by Django 2.1.3 on 2018-12-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20181112_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='repo',
        ),
        migrations.AddField(
            model_name='query',
            name='repo1',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='query',
            name='repo2',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='query',
            name='repo3',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
