# Generated by Django 2.1.3 on 2018-12-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20181207_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='name1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='name2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='name3',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
